#!/usr/bin/env python3
import sys
import argparse
from urllib.parse import urlencode
from urllib.parse import parse_qsl
from urllib.parse import parse_qs
from urllib.request import urlopen
import urllib
import configparser
from os.path import isfile
from os.path import expanduser
import json

#TODO change token and code to None for better readability. check if config supports that.
#TODO move debug output to classes, that's what verbose is for.

# config
api_base = 'https://getpocket.com/v3/'
add_url = api_base + 'add'
request_url =  api_base + 'oauth/request'
authorize_url = api_base + 'oauth/authorize'
get_url = api_base + 'get'

class AuthHandler:
	key = '11411-11f6716adafdbf8ee3401509'
	rc_file = expanduser('~/.pocketrc')
	config = configparser.ConfigParser(allow_no_value=True)
	token = ""
	verbose = False

	def __init__(self, verbose):
		self.verbose = verbose
		# load config, perform oauth if necessary
		if (not isfile(self.rc_file)):
			print("Config file not found, recreating.")
			self.config['OAUTH'] = {
					'code':'',
					'token':''
			}
			with open(self.rc_file, 'w') as configfile:
				self.config.write(configfile)

		self.config.read(self.rc_file)
		code = self.config['OAUTH']['code']
		self.token = self.config['OAUTH']['token']
		if (self.token == '' and code == ''):
			# no token, no code, start oauth
			code = self.oauth_code(self.key)
			self.config['OAUTH']['code'] = code
			with open(self.rc_file, 'w') as configfile:
				self.config.write(configfile)
			exit()
		elif (self.token == ''):
			# got code, get token
			self.token = self.oauth_token(self.key, code)
			self.config['OAUTH']['token'] = token
			with open(rc_file, 'w') as configfile:
				self.config.write(configfile)
			# else: everything shiny
	#oauth
	def oauth_code(self, key):
		values = {
				'consumer_key':key,
				'redirect_uri':'https://getpocket.com/connected_accounts'
		}
		
		response = self.request(values, request_url)
		code = response['code']
		message = ("Please open "
			"https://getpocket.com/auth/authorize?request_token=%s"
			"&redirect_uri=https://getpocket.com/connected_accounts"
			" in your browser, authorize pocket-cli and run pocket-cli again.")
		print(message % code)
		return code

	def oauth_token(self, key, reqcode):
		values = {
				'consumer_key':key,
				'code':reqcode
		}
		
		resp_objects = self.request(values, authorize_url)
		#print(resp_objects)
		token = resp_objects['access_token']
		return token

	def request(self, values, target_url):
		data = urlencode(values)
		data = data.encode('UTF-8')
		req = urllib.request.Request(target_url, data)
		response = urlopen(req)
		# error handling
		if (response.status != 200):
			raise Exception("Expected code 200, got %d" % response.status)
		# replace with parse_qs?
		return dict(parse_qsl(response.read().decode('UTF-8')))

class PocketHandler:
	auth = None
	verbose = False
	
	def __init__(self, auth, verbose):
		self.verbose = verbose
		self.auth = auth

	def create_values(self, optional):
		values = { 'consumer_key':self.auth.key, 'access_token':self.auth.token }
		for key,value in optional.items():
			values[key] = value
		return values

	def get_json(self, values, target_url):
		data = urlencode(values)
		data = data.encode('UTF-8')
		req = urllib.request.Request(target_url, data)
		response = urlopen(req)
		# error handling
		if (response.status != 200):
			raise Exception("Expected code 200, got %d" % response.status)
		return json.loads(response.read().decode('UTF-8'))


	def list_filtered(self, tag):
		values = self.create_values({'state':'all', 'tag':tag})
		json = self.get_json(values, get_url)['list']
		if not json:
			print("No results.")
		else:
			for item in sorted(json.values(), key=lambda item: item['sort_id']):
				print("%s: https://getpocket.com/a/read/%s"
					% (item['resolved_title'], item['item_id']))

	def list_unread(self):
		values = self.create_values({'state':'unread'})
		json = self.get_json(values, get_url)['list']
		if not json:
			print("No results")
		else:
			for item in sorted(json.values(), key=lambda item: item['sort_id']):
				print("%s: https://getpocket.com/a/read/%s"
					% (item['resolved_title'], item['item_id']))

	def add_to_pocket(self, url):
		values = self.create_values({'url':url})
		response = self.get_json(values, add_url)
		return int(response['item']['item_id'])

	def add_with_tags(self, url, tag_list):
		tags = self.concatenate_tags(tag_list)
		values = self.create_values({'url':url, 'tags':tags})
		response = self.get_json(values, add_url)
		return int(response['item']['item_id'])

	def concatenate_tags(self, tag_list):
		return ','.join(tag_list)

def main():
	# init parser
	parser = argparse.ArgumentParser(description=('A command line tool'
		'to manage your pocket items'))
	parser.add_argument('-a', '--add', metavar='URL', nargs='+',
		help='add the URL(s) to your pocket')
	parser.add_argument('-t', '--tag', metavar='TAG', nargs='+',
		help='add the TAG to the current item (specified by --add)')
	parser.add_argument('-u', '--unread', help='show a list of your unread items',
		action='store_true')
	parser.add_argument('-f', '--filter', metavar='TAG', nargs=1,
		help='show a list of all items with tag TAG')
	parser.add_argument('-v', '--verbose',
		help='print totally helpful debug messages',
		action='store_true')
	args = parser.parse_args()
	# parse arguments
	if not len(sys.argv) > 1:
		parser.print_help()
		exit(1)
	# we've got valid arguments, spawn stuff
	auth = AuthHandler(args.verbose)
	pocket = PocketHandler(auth, args.verbose)

	# debug stuff
	if args.verbose:
		print("DEBUG: Using access token %s." % pocket.token)
	# tag given, but no url to add the tag to
	if args.tag and not args.add:
		print("Currently --tag only works in conjuction with --add.")
	# new item
	if args.add:
		if args.tag:
			for url in args.add:
				item_id = pocket.add_with_tags(url, args.tag)
				print("Added URL '%s' as item %d, with tag %s."
						% (url, item_id, tags))
		else:
			for url in args.add:
				item_id = pocket.add_to_pocket(url)
				print("Added URL '%s' as item %d." %(url, item_id))
	# list unread items
	if args.unread:
		pocket.list_unread()
	# filter by tag
	if args.filter:
		if args.verbose:
			print("DEBUG: Filtering with tag '%s'." % args.filter[0])
		pocket.list_filtered(args.filter[0])

# call main method if not loaded as module
if __name__ == "__main__":
	main()
